# Generated by Django 3.0.3 on 2020-02-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='display_name',
            field=models.CharField(default='Unknown User', max_length=185),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='username',
            field=models.CharField(default='_anonyous', max_length=150),
            preserve_default=False,
        ),
    ]
