# Generated by Django 3.0.3 on 2020-03-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Destroy', 'Destroy'), ('Decommission', 'Decommission')], max_length=16),
        ),
    ]
