# Generated by Django 3.0.3 on 2020-02-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0002_auto_20200216_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='identifier',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
