# Generated by Django 3.0.3 on 2020-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0004_auto_20200226_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Destroy', 'Destroy')], max_length=16),
        ),
    ]
