variables:
  DB_HOST: database-1.clf9gopmww58.us-east-1.rds.amazonaws.com
  DB_USER: postgres
  DB_PASS: hyposoft
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  key: ${CI_COMMIT_REF_SLUG} # Each branch has its own node_modules in the cache
  paths:
  - app/hyposoft/frontend/node_modules/
  - .cache/pip
  - hyp_env

stages:
- build
- test
- staging
- deploy

build:
  stage: build
  script:
  # - apt-get update -q && apt-get install nodejs -yqq
  - python3 -V
  - pip3 install virtualenv
  - virtualenv hyp_env -p /usr/bin/python3
  - source hyp_env/bin/activate
  - /usr/bin/pip3 install -r requirements.txt
  - cd app/hyposoft/frontend
  - npm install
  - npm run build
  - cd ../../..
  tags:
  - dev

django_test:
  variables:
    DB_NAME: dev
  stage: test
  script:
  - python3 app/hyposoft/manage.py test
  except:
  - master
  tags:
  - dev

stage_dev:
  stage: staging
  variables:
    DB_NAME: dev
  script:
  - cd /home/gitlab-runner/
  - git clone git@gitlab.oit.duke.edu:ban20/hyposoft-group-8.git "$CI_COMMIT_SHORT_SHA-staging"
  - cd "$CI_COMMIT_SHORT_SHA-staging"
  - git checkout dev
  - cd app/hyposoft/frontent
  - npm install
  - npm run build
  - cd ..
  - python3 manage.py collectstatic --no-input
  only:
  - dev
  tags:
  - dev

deploy_dev:
  stage: deploy
  variables:
    DB_NAME: dev
  script:
  - rm -rf /home/gitlab-runner/hyposoft-deployed
  - mv -f /home/gitlab-runner/"$CI_COMMIT_SHORT_SHA-staging" /home/gitlab-runner/hyposoft-deployed
  - python3 /home/gitlab-runner/hyposoft-deployed/app/hyposoft/manage.py migrate
  - sudo uwsgi --reload /home/gitlab-runner/uwsgi.pid
  only:
  - dev
  tags:
  - dev
