# Generated by Django 3.0.3 on 2020-03-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0002_changeplan_auto_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
    ]
