# Generated by Django 3.0.3 on 2020-03-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0003_changeplan_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeplan',
            old_name='time_executed',
            new_name='executed_at',
        ),
    ]
