# Generated by Django 3.0.3 on 2020-03-30 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0003_auto_20200330_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdiff',
            name='changeplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
        migrations.AlterField(
            model_name='networkportdiff',
            name='changeplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
        migrations.AlterField(
            model_name='powereddiff',
            name='changeplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
        ),
    ]
