# Generated by Django 3.0.3 on 2020-03-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200330_0234'),
        ('power', '0002_auto_20200330_0234'),
        ('equipment', '0002_auto_20200330_0234'),
        ('changeplan', '0004_auto_20200330_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdiff',
            name='changed_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_asset', to='equipment.Asset'),
        ),
        migrations.AlterField(
            model_name='assetdiff',
            name='live_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_asset', to='equipment.Asset'),
        ),
        migrations.AlterField(
            model_name='networkportdiff',
            name='changed_networkport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_networkport', to='network.NetworkPort'),
        ),
        migrations.AlterField(
            model_name='networkportdiff',
            name='live_networkport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_networkport', to='network.NetworkPort'),
        ),
        migrations.AlterField(
            model_name='powereddiff',
            name='changed_powered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_powered', to='power.Powered'),
        ),
        migrations.AlterField(
            model_name='powereddiff',
            name='live_powered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_powered', to='power.Powered'),
        ),
    ]
