# Generated by Django 3.0.3 on 2020-03-29 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('changeplan', '0005_auto_20200328_1922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changeplan',
            unique_together={('owner', 'name')},
        ),
    ]
