# Generated by Django 3.0.2 on 2020-03-24 00:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu_model', models.CharField(blank=True, default='PDU Networx 98 Pro', max_length=64)),
                ('networked', models.BooleanField()),
                ('position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Powered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plug_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Asset must be plugged into a plug from 1 to 24 on this PDU.'), django.core.validators.MaxValueValidator(24, message='Asset must be plugged into a plug from 1 to 24 on this PDU.')])),
                ('on', models.BooleanField(default=False)),
                ('special', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Special network port ID must be at least 1'), django.core.validators.MaxValueValidator(2, message='Special network port ID must be no greater than 2')])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Asset')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.PDU')),
            ],
            options={
                'unique_together': {('special', 'asset'), ('plug_number', 'pdu')},
            },
        ),
        migrations.AddField(
            model_name='pdu',
            name='assets',
            field=models.ManyToManyField(through='power.Powered', to='equipment.Asset'),
        ),
        migrations.AddField(
            model_name='pdu',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Rack'),
        ),
        migrations.AlterUniqueTogether(
            name='pdu',
            unique_together={('rack', 'position')},
        ),
    ]
