# Generated by Django 3.0.3 on 2020-03-06 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0001_initial'),
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powered',
            name='version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
            preserve_default=False,
        ),
    ]
