# Generated by Django 3.0.3 on 2020-03-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0003_auto_20200330_0234'),
        ('equipment', '0002_auto_20200330_0234'),
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdu',
            name='pdu_model',
        ),
        migrations.AddField(
            model_name='powered',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together={('order', 'asset', 'version'), ('plug_number', 'pdu', 'version')},
        ),
        migrations.RemoveField(
            model_name='powered',
            name='special',
        ),
    ]
