# Generated by Django 3.0.3 on 2020-03-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0001_initial'),
        ('equipment', '0011_auto_20200306_0525'),
        ('power', '0002_auto_20200306_0410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdu',
            unique_together={('rack', 'position', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together={('special', 'asset', 'version'), ('plug_number', 'pdu', 'version')},
        ),
    ]
