# Generated by Django 3.0.3 on 2020-03-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0003_changeplan_parent'),
        ('equipment', '0021_auto_20200324_0555'),
        ('power', '0004_remove_pdu_pdu_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='powered',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together={('plug_number', 'pdu', 'version'), ('order', 'asset', 'version')},
        ),
        migrations.RemoveField(
            model_name='powered',
            name='special',
        ),
    ]
