# Generated by Django 3.0.3 on 2020-04-08 03:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_auto_20200401_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='BladeChassis',
            fields=[
                ('itmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.ITModel')),
            ],
            options={
                'verbose_name': 'Blade Chassis',
                'verbose_name_plural': 'Blade Chassis',
            },
            bases=('equipment.itmodel',),
        ),
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Chassis slot position must be at least 1.'), django.core.validators.MaxValueValidator(14, message='Chassis slot position must be at most 14.')])),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blade.BladeChassis')),
            ],
            options={
                'ordering': ('slot',),
                'unique_together': {('chassis', 'slot')},
            },
        ),
    ]
