# Generated by Django 3.0.3 on 2020-04-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200408_1849'),
        ('blade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blade',
            name='chassis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.Asset'),
        ),
    ]
