# Generated by Django 3.0.2 on 2020-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypo_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='datacenter_perm',
            field=models.CharField(choices=[('GLOBAL', 'Global')], default='', max_length=200, verbose_name='Datacenter Permission'),
        ),
    ]
