# Generated by Django 3.0.2 on 2020-03-24 00:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hypo_auth', '0002_permission_datacenter_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='datacenter_perm',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GLOBAL', 'Global'), ('RTP', 'Research Triangle Park')], max_length=10),
        ),
    ]
