# Generated by Django 3.0.2 on 2020-03-24 00:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hypo_auth', '0003_auto_20200324_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='datacenter_perm',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GLOBAL', 'Global'), ('RTP', 'Research Triangle Park')], max_length=10, verbose_name='Datacenter Permission'),
        ),
    ]
