# Generated by Django 3.0.2 on 2020-03-25 23:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hypo_auth', '0004_auto_20200324_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='datacenter_perm',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('GLOBAL', 'Global'), ('RTP', 'Research Triangle Park')], max_length=10, verbose_name='Datacenter Permission'),
        ),
    ]
