# Generated by Django 3.0.3 on 2020-03-30 05:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hypo_auth', '0005_auto_20200325_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='datacenter_perm',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('GLOBAL', 'Global'), ('RTP1', 'dc'), ('RTP2', 'dc'), ('RTP3', 'dc')], max_length=21, verbose_name='Datacenter Permission'),
        ),
    ]
