# Generated by Django 3.0.2 on 2020-03-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypo_auth', '0005_auto_20200325_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='datacenter_perm',
        ),
    ]
