# Generated by Django 3.0.2 on 2020-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyposoft', '0002_permissions_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permissions',
            name='Admin Permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='Asset Management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='Audit Permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='Model Management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='Power Permission',
            field=models.BooleanField(default=False),
        ),
    ]
