# Generated by Django 3.0.3 on 2020-03-04 04:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0009_auto_20200304_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPortLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16)),
                ('special', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Special network port ID must be at least 1'), django.core.validators.MaxValueValidator(4, message='Special network port ID must be no greater than 4')])),
                ('itmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.ITModel')),
            ],
            options={
                'unique_together': {('itmodel', 'special'), ('name', 'itmodel')},
            },
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Asset')),
                ('connection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.NetworkPort')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.NetworkPortLabel')),
            ],
            options={
                'unique_together': {('asset', 'label')},
            },
        ),
    ]
