# Generated by Django 3.0.3 on 2020-03-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0001_initial'),
        ('equipment', '0011_auto_20200306_0525'),
        ('network', '0002_networkport_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkport',
            unique_together={('asset', 'label', 'version')},
        ),
    ]
