# Generated by Django 3.0.3 on 2020-03-08 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200306_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkport',
            name='mac_address',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator('^([0-9a-fA-F]{2}[:_-]{0,1}){5}[0-9a-fA-F]{2}$', message='Your MAC Address must be in valid hexadecimal format (e.g. 00:1e:c9:ac:78:aa).')]),
        ),
    ]
