# Generated by Django 3.0.3 on 2020-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_auto_20200308_0535'),
        ('network', '0004_networkport_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkportlabel',
            name='order',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='networkportlabel',
            unique_together={('itmodel', 'order'), ('name', 'itmodel')},
        ),
        migrations.RemoveField(
            model_name='networkportlabel',
            name='special',
        ),
    ]
