# Generated by Django 3.0.3 on 2020-02-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkportlabel',
            unique_together={('itmodel', 'special'), ('name', 'itmodel')},
        ),
    ]
