# Generated by Django 3.0.3 on 2020-02-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkport',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.NetworkPortLabel'),
        ),
    ]
