# Generated by Django 3.0.3 on 2020-02-17 23:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator('^&|([a-zA-Z0-9](?:(?:[a-zA-Z0-9-]*|(?<!-)\\.(?![-.]))*[a-zA-Z0-9]+)?)$', message='Hostname must be compliant with RFC 1034.')])),
                ('rack_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rack position must be at least 1.')])),
                ('comment', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('(?m)(?![ \t]*(,|$))', message='Comments must be enclosed by double quotes if value contains line breaks.')])),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^$|^([0-9a-fA-F]{2}[:-_]{0,1}){5}[0-9a-fA-F]{2}$', message='Your MAC Address must be in valid hexadecimal format (e.g. 00:1e:c9:ac:78:aa).')])),
                ('asset_number', models.IntegerField(blank=True, default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Asset')),
                ('connection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.NetworkPort')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPortLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PDU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu_model', models.CharField(blank=True, default='PDU Networx 98 Pro', max_length=64)),
                ('position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Powered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plug_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Asset must be plugged into a plug from 1 to 24 on this PDU.'), django.core.validators.MaxValueValidator(24, message='Asset must be plugged into a plug from 1 to 24 on this PDU.')])),
                ('on', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Asset')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.PDU')),
            ],
            options={
                'unique_together': {('plug_number', 'pdu')},
            },
        ),
        migrations.AlterModelOptions(
            name='itmodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.RemoveField(
            model_name='rack',
            name='number',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='row',
        ),
        migrations.AddField(
            model_name='rack',
            name='rack',
            field=models.CharField(default='A0', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1,2}[1-9][0-9]{0,1}$', message='Row number must be specified by one or two capital letters.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='comment',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('(?m)(?![ \t]*(,|$))', message='Comments must be enclosed by double quotes if comment contains line breaks.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='display_color',
            field=models.CharField(blank=True, default='#ddd', max_length=10, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', message='Please enter a valid color code.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Height must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='memory',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of GB of memory must be at least 0.')], verbose_name='Memory (GB)'),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='power_ports',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of power ports must be at least 0.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='storage',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='itmodel',
            unique_together={('vendor', 'model_number')},
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.AddField(
            model_name='pdu',
            name='assets',
            field=models.ManyToManyField(through='equipment.Powered', to='equipment.Asset'),
        ),
        migrations.AddField(
            model_name='pdu',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Rack'),
        ),
        migrations.AddField(
            model_name='networkportlabel',
            name='itmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.ITModel'),
        ),
        migrations.AddField(
            model_name='networkport',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.NetworkPortLabel'),
        ),
        migrations.AddField(
            model_name='asset',
            name='datacenter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.Datacenter'),
        ),
        migrations.AddField(
            model_name='asset',
            name='itmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.ITModel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.Rack'),
        ),
        migrations.RemoveField(
            model_name='itmodel',
            name='ethernet_ports',
        ),
        migrations.AddField(
            model_name='rack',
            name='datacenter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='equipment.Datacenter'),
        ),
        migrations.AlterUniqueTogether(
            name='pdu',
            unique_together={('rack', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='networkportlabel',
            unique_together={('name', 'itmodel')},
        ),
        migrations.AlterUniqueTogether(
            name='networkport',
            unique_together={('label', 'asset')},
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('hostname', 'itmodel')},
        ),
    ]
