# Generated by Django 3.0.3 on 2020-02-25 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200225_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator('^$|^([0-9a-fA-F]{2}[:-_]{0,1}){5}[0-9a-fA-F]{2}$', message='Your MAC Address must be in valid hexadecimal format (e.g. 00:1e:c9:ac:78:aa).')]),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack',
            field=models.CharField(default='A0', max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{1,2}[0-9]{2}$', message='Row number must be specified by one or two capital letters.')]),
        ),
    ]
