# Generated by Django 3.0.3 on 2020-02-17 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200217_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='itmodel',
            name='network_ports',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of network ports must be at least 0.')]),
        ),
    ]
