# Generated by Django 3.0.2 on 2020-01-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200125_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itmodel',
            unique_together=set(),
        ),
    ]
