# Generated by Django 3.0.3 on 2020-02-22 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200221_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkportlabel',
            name='special',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Special network port ID must be at least 1'), django.core.validators.MaxValueValidator(4, message='Special network port ID must be no greater than 4')]),
        ),
        migrations.AlterUniqueTogether(
            name='networkportlabel',
            unique_together={('name', 'itmodel', 'special')},
        ),
    ]
