# Generated by Django 3.0.3 on 2020-02-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200222_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='itmodel',
            name='network_port_name_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_port_name_1', to='equipment.NetworkPortLabel'),
        ),
    ]
