# Generated by Django 3.0.3 on 2020-02-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200225_2232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together={('plug_number', 'pdu'), ('special', 'asset')},
        ),
    ]
