# Generated by Django 3.0.3 on 2020-02-19 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_itmodel_network_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='power_port_connection_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_port_connection_1', to='equipment.Powered'),
        ),
        migrations.AddField(
            model_name='asset',
            name='power_port_connection_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='power_port_connection_2', to='equipment.Powered'),
        ),
        migrations.AddField(
            model_name='itmodel',
            name='network_port_name_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_port_name_1', to='equipment.NetworkPortLabel'),
        ),
        migrations.AddField(
            model_name='itmodel',
            name='network_port_name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_port_name_2', to='equipment.NetworkPortLabel'),
        ),
        migrations.AddField(
            model_name='itmodel',
            name='network_port_name_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_port_name_3', to='equipment.NetworkPortLabel'),
        ),
        migrations.AddField(
            model_name='itmodel',
            name='network_port_name_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_port_name_4', to='equipment.NetworkPortLabel'),
        ),
        migrations.AddField(
            model_name='powered',
            name='label',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='datacenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.Datacenter'),
        ),
    ]
