# Generated by Django 3.0.2 on 2020-02-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200201_1847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itmodel',
            unique_together=set(),
        ),
    ]
