# Generated by Django 3.0.3 on 2020-02-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200219_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_1',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_3',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_4',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
