# Generated by Django 3.0.2 on 2020-02-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20200201_1858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itmodel',
            unique_together={('vendor', 'model_number')},
        ),
    ]
