# Generated by Django 3.0.3 on 2020-02-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200225_2345'),
        ('equipment', '0005_auto_20200226_0019'),
    ]

    operations = [
    ]
