# Generated by Django 3.0.3 on 2020-02-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_auto_20200219_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_port_name_1', to='equipment.NetworkPortLabel'),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_port_name_2', to='equipment.NetworkPortLabel'),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_port_name_3', to='equipment.NetworkPortLabel'),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='network_port_name_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_port_name_4', to='equipment.NetworkPortLabel'),
        ),
    ]
