# Generated by Django 3.0.3 on 2020-02-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20200222_2037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
    ]
