# Generated by Django 3.0.3 on 2020-02-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20200225_0143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkportlabel',
            unique_together={('name', 'itmodel'), ('itmodel', 'special')},
        ),
    ]
