# Generated by Django 3.0.2 on 2020-02-01 22:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0006_auto_20200201_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='rack_u',
        ),
        migrations.AddField(
            model_name='instance',
            name='rack_position',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Rack position must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='instance',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(?m)(?![ \t]*(,|$))', message='Comments must be enclosed by double quotes if value contains line breaks.')]),
        ),
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=64, null=True, validators=[django.core.validators.RegexValidator('(\\|)\\K(?=.{1,253}\x01)(?!.*--.*)(?P<fqdn>(?:(?![0-9-])[a-zA-Z0-9-]{1,63}(?<!-)\\.){1,}(?:(?![0-9-])[a-zA-Z0-9-]{1,63}(?<!-)))\x01', message='Hostname must be compliant with RFC 1034.')]),
        ),
        migrations.AlterField(
            model_name='instance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instance',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.Rack'),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator('(?m)(?![ \t]*(,|$))', message='Comments must be enclosed by double quotes if value contains line breaks.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='cpu',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='display_color',
            field=models.CharField(blank=True, default='#ddd', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', message='Please enter a valid color code.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Height must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='storage',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
