# Generated by Django 3.0.2 on 2020-02-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_merge_20200226_0023'),
        ('equipment', '0006_merge_20200226_0056'),
    ]

    operations = [
    ]
