# Generated by Django 3.0.2 on 2020-02-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20200201_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='owner',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='rack',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
