# Generated by Django 3.0.3 on 2020-02-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20200222_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('hostname', 'itmodel')},
        ),
    ]
