# Generated by Django 3.0.3 on 2020-02-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20200220_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itmodel',
            name='network_port_name_1',
        ),
        migrations.RemoveField(
            model_name='itmodel',
            name='network_port_name_2',
        ),
        migrations.RemoveField(
            model_name='itmodel',
            name='network_port_name_3',
        ),
        migrations.RemoveField(
            model_name='itmodel',
            name='network_port_name_4',
        ),
    ]
