# Generated by Django 3.0.3 on 2020-03-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20200226_0806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkportlabel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='networkportlabel',
            name='itmodel',
        ),
        migrations.AlterUniqueTogether(
            name='pdu',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pdu',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='pdu',
            name='rack',
        ),
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='powered',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='powered',
            name='pdu',
        ),
        migrations.DeleteModel(
            name='NetworkPort',
        ),
        migrations.DeleteModel(
            name='NetworkPortLabel',
        ),
        migrations.DeleteModel(
            name='PDU',
        ),
        migrations.DeleteModel(
            name='Powered',
        ),
    ]
