# Generated by Django 3.0.3 on 2020-02-22 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20200222_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(default='carter', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^&|([a-zA-Z0-9](?:(?:[a-zA-Z0-9-]*|(?<!-)\\.(?![-.]))*[a-zA-Z0-9]+)?)$', message='Hostname must be compliant with RFC 1034.')]),
        ),
    ]
