# Generated by Django 3.0.3 on 2020-02-21 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20200220_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powered',
            name='label',
        ),
        migrations.AddField(
            model_name='networkport',
            name='dest_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_asset', to='equipment.Asset'),
        ),
        migrations.AddField(
            model_name='networkport',
            name='dest_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dest_label', to='equipment.NetworkPortLabel'),
        ),
        migrations.AddField(
            model_name='networkport',
            name='src_asset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='src_asset', to='equipment.Asset'),
        ),
        migrations.AddField(
            model_name='networkport',
            name='src_label',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='src_label', to='equipment.NetworkPortLabel'),
        ),
        migrations.AlterUniqueTogether(
            name='networkport',
            unique_together={('src_label', 'src_asset')},
        ),
        migrations.RemoveField(
            model_name='networkport',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='networkport',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='networkport',
            name='label',
        ),
    ]
