# Generated by Django 3.0.2 on 2020-02-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20200201_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
