# Generated by Django 3.0.3 on 2020-03-06 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0001_initial'),
        ('equipment', '0009_auto_20200304_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='changeplan.ChangePlan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rack',
            name='datacenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.Datacenter'),
        ),
    ]
