# Generated by Django 3.0.3 on 2020-03-06 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0001_initial'),
        ('equipment', '0010_auto_20200306_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decommissioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rack',
            name='decommissioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^&|([a-zA-Z0-9](?:(?:[a-zA-Z0-9-]*|(?<!-)\\.(?![-.]))*[a-zA-Z0-9]+)?)$', message='Hostname must be compliant with RFC 1034.')]),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('hostname', 'version'), ('asset_number', 'version'), ('mac_address', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('rack', 'datacenter', 'version')},
        ),
    ]
