# Generated by Django 3.0.3 on 2020-02-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_auto_20200222_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkport',
            name='connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.NetworkPort'),
        ),
    ]
