# Generated by Django 3.0.3 on 2020-02-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_auto_20200221_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='power_port_connection_1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='power_port_connection_2',
        ),
    ]
