# Generated by Django 3.0.2 on 2020-02-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_auto_20200201_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='model_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='vendor',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
