# Generated by Django 3.0.2 on 2020-02-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_auto_20200201_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
