# Generated by Django 3.0.3 on 2020-03-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0001_initial'),
        ('equipment', '0012_auto_20200306_0529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('hostname', 'version'), ('mac_address', 'version'), ('asset_number', 'version')},
        ),
    ]
