# Generated by Django 3.0.2 on 2020-02-03 20:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0014_auto_20200202_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='number',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='row',
        ),
        migrations.AddField(
            model_name='rack',
            name='rack',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1,2}[1-9][0-9]{0,1}$', message='Row number must be specified by one or two capital letters.')]),
        ),
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=64, null=True, validators=[django.core.validators.RegexValidator('[a-z0-9][a-z0-9-]{0,62}', message='Hostname must be compliant with RFC 1034.')]),
        ),
        migrations.AlterField(
            model_name='instance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instance',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.Rack'),
        ),
    ]
