# Generated by Django 3.0.3 on 2020-03-06 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0014_auto_20200306_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decommissioned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decommissioned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='decommissioned_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='owned_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
