# Generated by Django 3.0.3 on 2020-02-22 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_auto_20200222_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^&|([a-zA-Z0-9](?:(?:[a-zA-Z0-9-]*|(?<!-)\\.(?![-.]))*[a-zA-Z0-9]+)?)$', message='Hostname must be compliant with RFC 1034.')]),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set(),
        ),
    ]
