# Generated by Django 3.0.3 on 2020-03-08 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeplan', '0002_changeplan_auto_created'),
        ('equipment', '0015_auto_20200306_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='decommissioned',
            field=models.CharField(choices=[('C', 'Commissioned')], default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{1,2}[0-9]{2}$', message='Row number must be specified by one or two capital letters.')]),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('hostname', 'version', 'decommissioned'), ('asset_number', 'version')},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='mac_address',
        ),
    ]
