# Generated by Django 3.0.2 on 2020-02-04 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_auto_20200203_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='comment',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator('(?m)(?![ \t]*(,|$))', message='Comments must be enclosed by double quotes if value contains line breaks.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(default='warn-no-host-set', max_length=64, validators=[django.core.validators.RegexValidator('[a-z0-9][a-z0-9-]{0,62}', message='Hostname must be compliant with RFC 1034.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.Rack'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='rack_position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rack position must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='comment',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.RegexValidator('(?m)(?![ \t]*(,|$))', message='Comments must be enclosed by double quotes if value contains line breaks.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='cpu',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='display_color',
            field=models.CharField(blank=True, default='#ddd', max_length=10, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$', message='Please enter a valid color code.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='model_number',
            field=models.CharField(default='warning! no model number set', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='power_ports',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Number of power ports must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='vendor',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{1,2}[1-9][0-9]{0,1}$', message='Row number must be specified by one or two capital letters.')]),
        ),
    ]
