# Generated by Django 3.0.2 on 2020-02-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_auto_20200204_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='rack',
        ),
        migrations.AddField(
            model_name='rack',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
