# Generated by Django 3.0.3 on 2020-02-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_auto_20200222_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkport',
            old_name='src_port',
            new_name='label',
        ),
        migrations.AddField(
            model_name='networkport',
            name='asset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='equipment.Asset'),
        ),
        migrations.AlterUniqueTogether(
            name='networkport',
            unique_together={('asset', 'label')},
        ),
        migrations.RemoveField(
            model_name='networkport',
            name='src_hostname',
        ),
    ]
