# Generated by Django 3.0.2 on 2020-02-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_auto_20200204_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itmodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
        migrations.AlterField(
            model_name='instance',
            name='itmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.ITModel', verbose_name='Model'),
        ),
    ]
