# Generated by Django 3.0.3 on 2020-03-20 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_auto_20200316_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='power_ports',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Number of power ports must be at least 0.')]),
        ),
    ]
