# Generated by Django 3.0.3 on 2020-03-21 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_auto_20200320_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmodel',
            name='network_ports',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='Number of network ports must be at least 0.')]),
        ),
    ]
