# Generated by Django 3.0.3 on 2020-02-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_auto_20200222_2213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together={('plug_number', 'pdu', 'special', 'asset')},
        ),
    ]
