# Generated by Django 3.0.3 on 2020-02-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_auto_20200223_2148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('hostname', 'itmodel')},
        ),
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together={('plug_number', 'pdu', 'special')},
        ),
    ]
