# Generated by Django 3.0.2 on 2020-02-05 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_auto_20200205_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rack number must be at least 1.')]),
        ),
        migrations.AlterField(
            model_name='rack',
            name='row',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{1,2}$', message='Row number must be specified by one or two capital letters.')]),
        ),
    ]
