# Generated by Django 3.0.3 on 2020-02-11 03:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0022_auto_20200205_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9](?:(?:[a-zA-Z0-9-]*|(?<!-)\\.(?![-.]))*[a-zA-Z0-9]+)?)$', message='Hostname must be compliant with RFC 1034.')])),
                ('rack_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rack position must be at least 1.')])),
                ('comment', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('(?m)(?![ \t]*(,|$))', message='Comments must be enclosed by double quotes if value contains line breaks.')])),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^([0-9a-f]{2}:){5}[0-9a-f]{2}$', message='Your MAC Address must be in valid hexadecimal format (e.g. 00:1e:c9:ac:78:aa).')])),
                ('asset_number', models.IntegerField(blank=True, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.AddField(
            model_name='asset',
            name='datacenter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.Datacenter'),
        ),
        migrations.AddField(
            model_name='asset',
            name='itmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.ITModel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.Rack'),
        ),
        migrations.AddField(
            model_name='rack',
            name='datacenter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='equipment.Datacenter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('hostname', 'itmodel')},
        ),
    ]
