# Generated by Django 3.0.3 on 2020-02-12 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_auto_20200205_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='model_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='instance',
            name='vendor',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^([a-zA-Z0-9](?:(?:[a-zA-Z0-9-]*|(?<!-)\\.(?![-.]))*[a-zA-Z0-9]+)?)$', message='Hostname must be compliant with RFC 1034.')]),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='memory',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of GB of memory must be at least 0.')], verbose_name='Memory (GB)'),
        ),
    ]
