# Generated by Django 3.0.3 on 2020-03-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_auto_20200328_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
