# Generated by Django 3.0.3 on 2020-02-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_auto_20200212_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='vendor',
        ),
    ]
