# Generated by Django 3.0.3 on 2020-02-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0025_auto_20200211_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdu',
            name='on',
        ),
        migrations.AddField(
            model_name='powered',
            name='on',
            field=models.BooleanField(default=False),
        ),
    ]
