# Generated by Django 3.0.3 on 2020-02-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0026_auto_20200211_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='assets',
            field=models.ManyToManyField(through='equipment.Powered', to='equipment.Asset'),
        ),
    ]
