# Generated by Django 3.0.3 on 2020-02-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0027_pdu_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itmodel',
            name='ethernet_ports',
        ),
        migrations.AlterField(
            model_name='rack',
            name='left_pdu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_for_rack', to='equipment.PDU'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='right_pdu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_for_rack', to='equipment.PDU'),
        ),
        migrations.CreateModel(
            name='NetworkPortLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16)),
                ('itmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.ITModel')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Asset')),
                ('connection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.NetworkPort')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.NetworkPortLabel')),
            ],
        ),
    ]
