# Generated by Django 3.0.3 on 2020-02-13 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0028_auto_20200211_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='pdu_model',
            field=models.CharField(blank=True, default='PDU Networx 98 Pro', max_length=64),
        ),
        migrations.AlterField(
            model_name='itmodel',
            name='memory',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Number of GB of memory must be at least 0.')], verbose_name='Memory (GB)'),
        ),
    ]
