# Generated by Django 3.0.3 on 2020-02-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0030_auto_20200213_0420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkport',
            unique_together={('label', 'asset')},
        ),
        migrations.AlterUniqueTogether(
            name='powered',
            unique_together={('plug_number', 'pdu')},
        ),
    ]
