# Generated by Django 3.0.3 on 2020-02-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_auto_20200213_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='on_left',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
