# Generated by Django 3.0.3 on 2020-02-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0032_auto_20200213_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='left_pdu',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='right_pdu',
        ),
        migrations.AddField(
            model_name='pdu',
            name='position',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdu',
            name='rack',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equipment.Rack'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pdu',
            unique_together={('rack', 'position')},
        ),
        migrations.RemoveField(
            model_name='pdu',
            name='on_left',
        ),
    ]
