# Generated by Django 3.0.3 on 2020-02-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0034_auto_20200217_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='abbr',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
