# Generated by Django 3.0.3 on 2020-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0036_auto_20200219_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='networked',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
