# Generated by Django 3.0.3 on 2020-02-21 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0038_auto_20200220_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1,2}[0-9]{2}$', message='Row number must be specified by one or two capital letters.')]),
        ),
    ]
