# Generated by Django 3.0.2 on 2020-02-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0039_auto_20200220_2301'),
        ('equipment', '0039_auto_20200221_0407'),
    ]

    operations = [
    ]
