# Generated by Django 3.0.2 on 2020-03-22 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hyposoft', '0003_auto_20200322_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Perms',
        ),
    ]
