# Generated by Django 3.0.2 on 2020-03-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyposoft', '0004_auto_20200322_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perms',
            name='Admin Permission',
        ),
        migrations.RemoveField(
            model_name='perms',
            name='Asset Management',
        ),
        migrations.RemoveField(
            model_name='perms',
            name='Audit Permission',
        ),
        migrations.RemoveField(
            model_name='perms',
            name='Model Management',
        ),
        migrations.RemoveField(
            model_name='perms',
            name='Power Permission',
        ),
        migrations.AddField(
            model_name='perms',
            name='admin_perm',
            field=models.BooleanField(default=False, verbose_name='Admin Permission'),
        ),
        migrations.AddField(
            model_name='perms',
            name='asset_perm',
            field=models.BooleanField(default=False, verbose_name='Asset Management'),
        ),
        migrations.AddField(
            model_name='perms',
            name='audit_perm',
            field=models.BooleanField(default=False, verbose_name='Audit Permission'),
        ),
        migrations.AddField(
            model_name='perms',
            name='model_perm',
            field=models.BooleanField(default=False, verbose_name='Model Management'),
        ),
        migrations.AddField(
            model_name='perms',
            name='power_perm',
            field=models.BooleanField(default=False, verbose_name='Power Permission'),
        ),
    ]
